
const DATA=window.OC_DATA;const LABS=DATA.labs;const KEY='chubu_oc_2026_stamps_v3';let currentDay=7;let selectedBuilding='30号館';
const now=new Date();if(now.getMonth()===7&&[7,8,9].includes(now.getDate()))currentDay=now.getDate();const dayParam=Number(new URLSearchParams(location.search).get('day'));if([7,8,9].includes(dayParam))currentDay=dayParam;
function got(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}function save(x){localStorage.setItem(KEY,JSON.stringify(x))}
async function sha256(s){const data=new TextEncoder().encode(s.toUpperCase());const hash=await crypto.subtle.digest('SHA-256',data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,'0')).join('')}
function buildingClass(b){return {'30号館':'b30','32号館':'b32','33号館':'b33','11号館':'b11','33号館北プレハブ棟':'bp'}[b]||'bp'}
function buildingColor(b){return {'30号館':'#4e8df6','32号館':'#9066d8','33号館':'#f59a35','11号館':'#e65b94','33号館北プレハブ棟':'#3d9e9a'}[b]||'#3d9e9a'}
function render(){const stamps=got();document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',+x.dataset.day===currentDay));document.getElementById('status').textContent=DATA.dates[currentDay]+'｜取得済み '+Math.min(stamps.length,4)+' / 4';document.getElementById('progress').innerHTML=[0,1,2,3].map(i=>`<div class="dot ${i<stamps.length?'done':''}">${i<stamps.length?'✓':i+1}</div>`).join('');document.getElementById('complete').classList.toggle('show',stamps.length>=4);const openLabs=LABS.filter(l=>l.days.includes(currentDay));document.getElementById('labs').innerHTML=openLabs.map(l=>`<article class="lab ${stamps.includes(l.id)?'done':''}"><h3>${stamps.includes(l.id)?'✓ ':''}${l.name}</h3><p>${l.fields}</p><span class="loc">${l.building}｜${l.floor}</span></article>`).join('');renderBuildingCards();renderFloor()}
function renderBuildingCards(){document.getElementById('buildingCards').innerHTML=DATA.buildingOrder.map(b=>{const count=LABS.filter(l=>l.building===b&&l.days.includes(currentDay)).length;return `<button class="building-card ${buildingClass(b)} ${selectedBuilding===b?'active':''}" data-building="${b}">${b}<small>本日 ${count}研究室</small></button>`}).join('');document.querySelectorAll('.building-card').forEach(b=>b.onclick=()=>{selectedBuilding=b.dataset.building;renderBuildingCards();renderFloor();document.getElementById('floorShell').scrollIntoView({behavior:'smooth',block:'nearest'})})}
function roomHTML(l,stamps){const open=l.days.includes(currentDay),done=stamps.includes(l.id);return `<div class="room ${open?'open':'closed'} ${done?'done':''}"><b>${done?'✓ ':''}${l.name}</b><div class="room-status">${open?'本日公開':'本日は非公開'}${done?'・取得済み':''}</div></div>`}
function renderFloor(){const root=document.getElementById('floorShell'),stamps=got();root.classList.add('show');const floors=DATA.floorOrder[selectedBuilding]||[];root.innerHTML=`<div class="floor-title"><h3>${selectedBuilding} 階別マップ</h3><button class="closemap" onclick="document.getElementById('floorShell').classList.remove('show')">閉じる</button></div><p class="note">添付の館内図をもとに、廊下・エレベーター・階段と研究室の位置関係が分かる簡易図にしています。</p><div class="floor-stack">${floors.map(f=>{const ls=LABS.filter(l=>l.building===selectedBuilding&&l.floor===f);const left=ls.filter((_,i)=>i%2===0),right=ls.filter((_,i)=>i%2===1);return `<section class="floor-plan"><div class="floor-banner" style="background:${buildingColor(selectedBuilding)}"><span>${selectedBuilding} ${f}</span><span>${ls.filter(l=>l.days.includes(currentDay)).length} OPEN</span></div><div class="plan-body"><div class="room-column">${left.map(l=>roomHTML(l,stamps)).join('')||'<div class="room closed">研究室登録なし</div>'}</div><div class="corridor">廊下</div><div class="room-column">${right.map(l=>roomHTML(l,stamps)).join('')||'<div class="room closed">研究室登録なし</div>'}</div></div>${selectedBuilding==='32号館'?'<div class="connection">→ 33号館へ連絡通路で接続</div>':''}</section>`}).join('')}</div>`}
function openPassword(){document.getElementById('pw').value='';document.getElementById('err').textContent='';document.getElementById('modal').classList.add('show');setTimeout(()=>document.getElementById('pw').focus(),80)}function closePassword(){document.getElementById('modal').classList.remove('show')}
async function submitPassword(){const val=document.getElementById('pw').value.trim().toUpperCase();if(!val){document.getElementById('err').textContent='合言葉を入力してください。';return}const hash=await sha256(val);const lab=LABS.find(l=>l.passwordHash===hash);if(!lab){document.getElementById('err').textContent='合言葉が違います。研究室スタッフにご確認ください。';return}if(!lab.days.includes(currentDay)){document.getElementById('err').textContent='この研究室は本日の公開対象ではありません。日付をご確認ください。';return}const stamps=got();if(stamps.includes(lab.id)){document.getElementById('err').textContent=lab.name+'のスタンプは取得済みです。';return}stamps.push(lab.id);save(stamps);closePassword();render();showFx(lab,stamps.length)}
function particles(){const fx=document.getElementById('stampFx');fx.querySelectorAll('.confetti,.spark').forEach(x=>x.remove());const colors=['#ffcb3d','#fff','#54e7a2','#ff77b6','#69a8ff','#ff8e45'];for(let i=0;i<70;i++){const c=document.createElement('i');c.className='confetti';c.style.left=Math.random()*100+'vw';c.style.background=colors[i%colors.length];c.style.animationDelay=Math.random()*.55+'s';c.style.animationDuration=(1.35+Math.random()*1.2)+'s';c.style.setProperty('--drift',(-130+Math.random()*260)+'px');fx.appendChild(c)}for(let i=0;i<38;i++){const s=document.createElement('i');s.className='spark';s.style.left=(50+(-10+Math.random()*20))+'%';s.style.top=(45+(-10+Math.random()*20))+'%';s.style.animationDelay=Math.random()*.3+'s';s.style.setProperty('--sx',(-240+Math.random()*480)+'px');s.style.setProperty('--sy',(-240+Math.random()*480)+'px');fx.appendChild(s)}}
function showFx(lab,count){const fx=document.getElementById('stampFx'),complete=count>=4;fx.classList.toggle('completefx',complete);document.getElementById('fxIcon').textContent=complete?'🏆':'★';document.getElementById('fxTitle').textContent=complete?'4 STAMPS COMPLETE!':'STAMP GET!';document.getElementById('fxLab').textContent=lab.name;document.getElementById('fxCount').textContent=complete?'コンプリート達成！':count+' / 4 スタンプ';particles();fx.classList.add('show');document.body.style.overflow='hidden';if(navigator.vibrate)navigator.vibrate(complete?[100,50,140,60,200]:[70,35,90])}
function closeFx(){const fx=document.getElementById('stampFx'),complete=fx.classList.contains('completefx');fx.classList.remove('show');document.body.style.overflow='';if(complete)setTimeout(()=>document.getElementById('complete').scrollIntoView({behavior:'smooth',block:'center'}),120)}function resetRally(){if(confirm('取得済みスタンプをすべて消去しますか？')){localStorage.removeItem(KEY);render()}}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{currentDay=+b.dataset.day;render()});document.getElementById('pw').addEventListener('keydown',e=>{if(e.key==='Enter')submitPassword()});document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal')closePassword()});document.getElementById('stampFx').addEventListener('click',e=>{if(e.target.id==='stampFx')closeFx()});render()});
